### PR TITLE
New setting

### PR DESCRIPTION
**Pull request by mariogrip**
Added Language setting

Is this design something that you will like?
http://getbootstrap.com/examples/dashboard/ 

And i also working on a cloud website where you can access your minepeon.

-Mariogrip

### CODE REVIEW

**Comment by MineForeman** [comment]
Hi,

I have that dashboard bookmarked!  I was planning to start work on it soon, I was wanting to implement it myself so I could learn more about bootstrap and twitter.  Apart from the basic features of bootstrap I don't know nearly enough.

Neil

**Comment by mariogrip** [comment]
I can start working on implementing that dashboard if you want.

-Mariogrip

**Comment by MineForeman** [comment]
I would like to do it (I really need to learn).

I am going to be doing a few merges of branches over the next few days to get everything as clean as possible but I plan to tackle it this weekend.

What I would really like to see is an example of a "real live plugin" using your code!

**Comment by mariogrip** [comment]
https://github.com/mariogrip/minepeon-plugin-MobileMinerApp

Here is Mobile Miner App Plugin using the new plugin system. I haven't tested it, Because i'm don't have access to my raspberry right now. I will test it when i'm home...

-Mariogrip

**Comment by mariogrip** [comment]
Tested and fully working now

The file: 
https://raw.github.com/mariogrip/minepeon-plugin-MobileMinerApp/master/minepeon-plugin-MobileMinerApp.tar.gz

You can just copy and paste the link into "Install plugin from web" and hit install!

**Pull request merged**
