### PR TITLE
Ajax Update, live status update

### PR DESCRIPTION
**Pull request by mariogrip**
I added this to 0.3.0 branch for testing, (ajax + minepeon looks awesome!)

### CODE REVIEW

**Comment by mariogrip** [comment]
Added bug fix for: header locate loop in setup.php

**Comment by MineForeman** [comment]
Gah, I have just realised that I am working from your git repo and I can no longer pull this!

Can you push again and I need to sort my local repo out.

Neil

**Comment by mariogrip** [comment]
Give me a message when you want the new push.

**Comment by MineForeman** [comment]
Any time you are ready.

I am going to make a fork when you have and start to put it onto the new OS.

Do you have a BeagleBone Black by the way?  Much faster to develop on and the USB support is 10x better with my new kernel.  If you don't I can probably order one off adafruit for you.  (they accept bitcoin and I need another one as well)

Neil

**Pull request closed without merging**
