### PR TITLE
Ajax Update, live status update

### PR DESCRIPTION
**Pull request by mariogrip**
I added this to 0.3.0 branch for testing, (ajax + minepeon looks awesome!)

(I do not have an BeagleBone Black)

### CODE REVIEW

**Comment by mariogrip** [comment]
btw, how does ajax works for you? (it runs perfect on RPi, how does it perform on a BBb?)

**Comment by mariogrip** [comment]
I might add a setting to edit refresh time and option to disable live update.

**Comment by MineForeman** [comment]
It runs great on the BBB as well.  Email me your postal address and I will get one on its way to you (along with a serial cable and a few SD's)

I still cannot pull this, did you re-sysnc before you pushed?

**Comment by mariogrip** [comment]
Humm, Yeah, i did re-sync, it should be up to date with branch 0.3.0. I have some more stuff to push, but i will wait until this is fixed.

(How about adding me as an github collaborator?)

-Mariogrip (did you get my e-mail?)

**Comment by MineForeman** [comment]
Still wont merge.

I will try with the command line.

**Comment by mariogrip** [comment]
Ah, i see the problem. give me an minute to fix that.

**Comment by mariogrip** [comment]
did you add all my commits from my branch "master" to your "master"?

**Comment by MineForeman** [comment]
Yeah, that is the issue.  I (should) only merge branches to master and 0.3.0 is not ready for that.

If you could do it against 0.3.0 that would be great.

**Comment by mariogrip** [comment]
Now my fork is fixed (now you can add me as an collaborator if you want, or do you want me to send a pull request)

**Comment by MineForeman** [comment]
Can you send a pull.

I am looking at adding you as a contributor but I am having trouble getting fine grained access to repo's.  I have several private repo's that have other stuff in it that I cannot let out (hashfast and spondoolies).

Neil

**Pull request closed without merging**
