### PR TITLE
MobileMinerApp integration

### PR DESCRIPTION
**Pull request by ghost**
Includes the files needed for MobleMinerApp integration (mobileminerapp.com). 

Settings will need to be added to the minepeon.conf file; `sudo nano /opt/minepeon/etc/minepeon.conf`

```
"mma_machineName": "MinePeon"    # can be user defined, if running multiple MinePeons, suggest changing this for each MinePeon, may just grabd the host name later on.
"mma_userEmail": "USER_EMAIL"    # user defined, email used to receive appKey on MobileMinerApp.com.
"mma_appKey": "USER_APPKEY"      # user defined, app key from MobileMinerApp.com.
"mma_checkInterval": 20,         # default is 20, this is the interval delay in seconds as to how often MinePeon updates and checks for commands.
"mma_coinName": "Bitcoin"        # default Bitcoin.
"mma_coinSymbol": "BTC"          # default BTC.
"mma_alogorithm": "SHA-256"      # default SHA-256.
"mma_cronLog": false             # Set this to true if you want the cron to output success messages to the log file.
```

Need to add a few lines to the crontab (do not use sudo when doing this); `EDITOR=nano crontab -e`

```
*/1 * * * * /usr/bin/php /opt/minepeon/etc/cron.d/webcron/mobileminerapp.cron.php update >> /opt/minepeon/log/mma_update.log
*/2 * * * * /usr/bin/php /opt/minepeon/etc/cron.d/webcron/mobileminerapp.cron.php check >> /opt/minepeon/log/mma_check.log
```

### CODE REVIEW

**Comment by thgh** [comment]
A couple remarks:
- Consider including settings.inc.php, it sets the timezone and loads all settings.
- What happens when not all settings are set?
- I just noticed that Neil added some commands in etc/init.d
- There should be a way to disable this mma module including cronjobs, I started working on a simple solution. See issues.

**Comment by ghost** [comment]
Could easily just add a mma_enabled setting somewhere and have it check said setting, if so, the cron jobs will 'run' but not execute anything, basically it'll run, see it's not enabled and exit. Probably the best solution seeing how often MMA needs updates to the server. Also, I'll put some clauses in to where if the required data (appkey, email) isn't filled out, it'll just exit or throw an exception. Modifying the cronjobs on the fly (automatically) is something I would advice against (as error can happen with that), so this way, you don't need to modify the cron jobs, just it disabled the cron job from doing anything.

**Comment by thgh** [comment]
Thanks for adding the mmaEnable hook

Maybe it's a good idea that I put all settings in an array like this:

```
...,
"mmaEnable" : true,
"mma" : {
    "coinSymbol",
    ...
},
...
```

This saves some lines of code in both

I would like to copy the exact api names from http://www.mobileminerapp.com/#api
OK?

This is what I have at this moment:
captureha

**Comment by ghost** [comment]
Either way, if it's JSON it's readable to me... 

Looking good.

**Comment by thgh** [comment]
Alright, settings committed

And indeed, the names don't matter that much because app[] makes a complete new element anyway. But it will be good not seeing alogorithm :-)

**Comment by MineForeman** [comment]
cgminer... JSON
bfgminer.... JSON
bitcoind.... JSON
php.... JSON
pooldata....  JSON

We would be mad to use anything else.

Neil

P.S. 90% of the time I use CSV :P .

On 16 September 2013 13:54, thgh notifications@github.com wrote:

> Alright, settings committed
> 
> And indeed, the names don't matter that much because app[] makes a
> complete new element anyway. But it will be good not seeing alogoritms :-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MineForeman/minepeon-base/pull/1#issuecomment-24485530
> .

## 

[image: Facebook] https://www.facebook.com/MineForeman
[image: Twitter] https://twitter.com/mineforeman
[image: LinkedIn] http://www.linkedin.com/company/mineforeman-com
Neil Fincham
MineForeman
Phone: +64 21 545 583
C/O PF Olsen, 99 Sala St, Rotorua, New Zealand. 3010
Website http://mineforeman.com/ | neil@mineforeman.com

**Comment by ghost** [comment]
haha, yea...
I usually use CSV when working with database exports/imports, but these days it's mostly JSON or XML or a version of XML called something stupid, cause it's really just XML.

**Comment by henrylwilliams** [comment]
Not sure why this got closed by me; Regardless, I had to create a new account for personal stuff, per potential legal reasons (since my other account is mainly for work). Which kind of sucks, since I deleted this very account the other day just to finally switch to one account, but whatever.

**Comment by MineForeman** [comment]
I assure you that I did not close it.

I probably would not have pull'ed it though.  I am trying to work out the
best way to include code like this (you were in on the conversation).

Still mulling things over in my mind.... plugin code.  I want it :P

Neil

On 18 September 2013 09:02, labmixz notifications@github.com wrote:

> Not sure why this got closed by me; Regardless, I had to create a new
> account for personal stuff, per potential legal reasons (since my other
> account is mainly for work). Which kind of sucks, since I deleted this very
> account the other day just to finally switch to one account, but whatever.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MineForeman/minepeon-base/pull/1#issuecomment-24622124
> .

## 

[image: Facebook] https://www.facebook.com/MineForeman
[image: Twitter] https://twitter.com/mineforeman
[image: LinkedIn] http://www.linkedin.com/company/mineforeman-com
Neil Fincham
MineForeman
Phone: +64 21 545 583
C/O PF Olsen, 99 Sala St, Rotorua, New Zealand. 3010
Website http://mineforeman.com/ | neil@mineforeman.com

**Comment by henrylwilliams** [comment]
Understandable and yea, I remember the conversation, still awaiting to hear your plan, there are a lot of ways to do it, but question is which was is going to be most efficient for the rPi

**Comment by henrylwilliams** [comment]
Plus, I've got to fix some things this weekend to get the stats from BFGMiner working as well, not sure how I missed that.

**Pull request closed without merging**
