### PR TITLE
Bug fixses

### PR DESCRIPTION
**Pull request by mariogrip**
Don't delete while donating.
and
bug fix on update system

Also added sleep between disablepool and removepool, seems to be more stable.

### CODE REVIEW

**Comment by MineForeman** [comment]
Cool, I am just about finished with the apache 2.2 to 2.4 stuff.  Any luck I can make an image of this tonight.

**Comment by mariogrip** [comment]
we might create a branch named update and test the update system, i have just tested it pulling form my git. but it should work.

**Comment by MineForeman** [comment]
Just running through my test's.  There is still a condition that the donate pool may remain active.

If the miner crashes after donateActive is set to true then after a reboot DONATE will not be running to set it to false so CHECKDonate wont remove the pool.

It also needs to check that hour <> 12 and donate time is not running (if you get my meaning).

**Comment by MineForeman** [comment]
Also (sorry about this, just testing and these things come up);-

Nothing should be done if the donate pool is the only pool.  That happens when the image is shipped.

**Comment by mariogrip** [comment]
Is there 2 different users on the donate mining pool?

example: one is for "auto donate" and the second is for "manual donate".

**Comment by MineForeman** [comment]
Good idea, there is now.

MinePeon_ManualDonate

Problem fixed

**Pull request merged**
