### PR TITLE
Added about, contact and license to one file

### PR DESCRIPTION
**Pull request by mariogrip**
and added "beta" to navbar. like [small]beta[small] minepeon

### CODE REVIEW

**Comment by mariogrip** [comment]
Then everything looks ready to Update image :)

**Comment by mariogrip** [comment]
This update has some big improvements, so i hope people will love this update :)

**Comment by mariogrip** [comment]
Are you gonna push a new version today? and how did the testing of the update system work for you?

**Comment by MineForeman** [comment]
I am going to try, sorry when I got home I was exhausted and went to sleep.

The updates system works great.  It does not take into account the OS, but that is another story.  One thing I that needs to be addressed is that  un-installing a plugin does not remove settings/all files.  Not a biggie though, I just need to pay attention when packaging.

I am making a "Developer" hidden part on the board so we can communicate better.  (Our different time zones are getting in the way)

Neil

**Comment by mariogrip** [comment]
About un-installing, you can create a uninstall.xml file that look like this

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<uninstal>
<run_sh_file>uninstal.sh</run_sh_file>
</uninstal>
```

Then it will run a .sh file that can remove all files that the plugin includes.

**Comment by MineForeman** [comment]
Gah... piles of fixes cleaned up heaps of stuff moved the update.xml and plugin.xml to github so we can both easily use it here;-

https://github.com/MineForeman/MinePeon-Updates

And it wont open https .....  I am going to bed.  No update image today.  When you get up can you have a look?

Neil

P.S. pull to your repo's before you do anything, I have tidied up a lot of stuff and found and declared undeclared variables.  You need to fix your no language file cos I did not know what to put for a few that were missing ;) .

**Pull request merged**
