### PR TITLE
Update

### PR DESCRIPTION
**Pull request by mariogrip**
Hi,

Ok, this need some testing.

What this do now:

Run a .sh at install (if the plugin require it)
Run s .sh at uninstall (if the plugin require it)
redirect after install (if the plugin require it)
list plugins
Install plugins
Download and install
Remove
plugin settings
add to menu
What is work in progress:

setting api
pool api
language
Tell me if there is something that you don't like.

I also started on language.

### CODE REVIEW

**Comment by mariogrip** [comment]
I will work more with Language. I will also translate to norwegian

**Comment by MineForeman** [comment]
Can you pull and then push, I am getting errors saying it need merging.

Neil

**Comment by mariogrip** [comment]
Now

**Comment by MineForeman** [comment]
Thanks.  I had actually thought you had lost interest and all this time you have had a pull waiting!

I apologise wholeheartedly.

**Pull request merged**
