### PR TITLE
Error output, when error

### PR DESCRIPTION
**Pull request by mariogrip**

### CODE REVIEW

**Comment by MineForeman** [comment]
Can you put a bit more thought into naming your commit's, "Error output, when error" does not tell me much.

**Comment by MineForeman** [comment]
Did you get anywhere with the https for the xml files by the way?  I can have a go at it now if you want.

Neil

**Comment by mariogrip** [comment]
For HTTPs to work, PHP needs the openssl extension. do we need them to be https?

**Comment by mariogrip** [comment]
it looks like github doesn't support xml... you cannot use github, it just outputs a raw text.

**Comment by MineForeman** [comment]
I was trying to link it to this file in a repo;-

https://raw.github.com/MineForeman/MinePeon-Updates/master/update.xml

If it is http it redirects to https.  I wanted it there for 2 reasons;-
1.  Both you and I (and anyone else) can modify it.
2. We don't get accused of spying on MinePeon users.

Neil

**Comment by MineForeman** [comment]
Just looking to see what it would take to get openssl support for PHP, would that fix it?

Neil

**Comment by mariogrip** [comment]
I guess not, github is outputs raw text, not in xml format like this

http://mariogrip.com/minepeon/plugins.xml

**Comment by MineForeman** [comment]
Bugger!

Can we fopen it and parse it into XML?

**Comment by mariogrip** [comment]
how about the server is syncing from git?

**Comment by mariogrip** [comment]
if you have ssh on minepeon's server you can use DVCS to auto syncing.

**Comment by mariogrip** [comment]
file_put_contents('plugin.xml', file_get_contents('http://github.com'));

this might work, i can test it.

**Comment by MineForeman** [comment]
That would be my choice as a solution, much more simple than DVCS.

Can you not just ;-

simplexml_load_string(file_get_contents('https://raw.github.com/MineForeman/MinePeon-Updates/master/update.xml));

?

**Comment by mariogrip** [comment]
nope, still not accepting. i don't know if it is https that block or something else.

**Comment by mariogrip** [comment]
My server is now setup to auto sync github

http://mariogrip.com/minepeon/update.xml
http://mariogrip.com/minepeon/plugins.xml

**Comment by MineForeman** [comment]
We need to find an alternative solution (not DVCS), the user has no choice that these checks are made and this will look like we are gathering information on MinePeon users.

**Comment by mariogrip** [comment]
okey, i will try to find something that works.

**Comment by mariogrip** [comment]
Yeah! this is how: 

in php.ini
find
;extension=openssl.so
and remove:
;
line 882 btw

**Comment by MineForeman** [comment]
Excellent, looking good.  I am just compiling the HEX drivers and will start my tests for a release.

Can you look at the forums, I have started a "release notes" for this.  Add as much and take credit for as you can!

**Comment by mariogrip** [comment]
humm, i cannot see any "release notes". where is it on the forum?

**Comment by MineForeman** [comment]
Way down at the bottom in the hidden area.

**Comment by mariogrip** [comment]
we may get a better way to communicate then this :P

**Comment by mariogrip** [comment]
I guess i cannot access hidden area, cannot find any.

**Comment by MineForeman** [comment]
LOL, I know, that is what that developer area is for.  This is like using hand signals.

I also want to discuss future plans I have and you may have, but that is once we get this release out.

**Comment by MineForeman** [comment]
Try now

**Comment by mariogrip** [comment]
Yes, now it works

**Comment by MineForeman** [comment]
It is not rally secret, it is just somewhere that developers can discuss stuff without interruption.

**Comment by mariogrip** [comment]
Added some stuff :)

**Comment by MineForeman** [comment]
Something is not right;-

cat /opt/minepeon/etc/version
0.2.4.6

https://raw.github.com/MineForeman/MinePeon-Updates/master/update.xml

says 0.2.4.6

But I am getting flagged for an update anyway

**Comment by mariogrip** [comment]
Diggin in to that

**Comment by mariogrip** [comment]
it's working for me, give it a update

```
sudo run-parts /opt/minepeon/etc/cron.d/hourly
```

**Comment by MineForeman** [comment]
NEVER run that as root by the way, you sill screw your permissions ;) .  I will try it as minepeon.

**Comment by mariogrip** [comment]
I love root, Then i got the power i want :P hehe

**Comment by MineForeman** [comment]
run-parts /opt/minepeon/etc/cron.d/hourly
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:32: parser error : Specification mandate value for attribute data-pjax-transient in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():     <meta name="selected-link" value="repo_source" data-pjax-transient /> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                                                        ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:53: parser error : Specification mandate value for attribute data-pjax-transient in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():         <link data-pjax-transient rel='permalink' href='/MineForeman/MinePeon-Up in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                   ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:53: parser error : attributes construct error in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():         <link data-pjax-transient rel='permalink' href='/MineForeman/MinePeon-Up in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                   ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:53: parser error : Couldn't find end of Start Tag link line 53 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():         <link data-pjax-transient rel='permalink' href='/MineForeman/MinePeon-Up in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                   ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:60: parser error : Opening and ending tag mismatch: meta line 51 and head in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():   </head> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():          ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:136: parser error : Opening and ending tag mismatch: input line 134 and form in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): </form> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():        ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:137: parser error : Opening and ending tag mismatch: input line 95 and div in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():     </div> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():           ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:139: parser error : Opening and ending tag mismatch: form line 93 and div in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():   </div> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():         ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:145: parser error : Specification mandate value for attribute itemscope in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():           <div class="site" itemscope itemtype="http://schema.org/WebPage"> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                       ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:145: parser error : attributes construct error in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():           <div class="site" itemscope itemtype="http://schema.org/WebPage"> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                       ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:145: parser error : Couldn't find end of Start Tag div line 145 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():           <div class="site" itemscope itemtype="http://schema.org/WebPage"> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                       ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:179: parser error : Specification mandate value for attribute itemscope in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():         <h1 itemscope itemtype="http://data-vocabulary.org/Breadcrumb" class="en in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                       ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:179: parser error : attributes construct error in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():         <h1 itemscope itemtype="http://data-vocabulary.org/Breadcrumb" class="en in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                       ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:179: parser error : Couldn't find end of Start Tag h1 line 179 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():         <h1 itemscope itemtype="http://data-vocabulary.org/Breadcrumb" class="en in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                       ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:192: parser error : Opening and ending tag mismatch: div line 148 and h1 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():         </h1> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():              ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:266: parser error : Opening and ending tag mismatch: input line 262 and div in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():   </div> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():         ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:280: parser error : Opening and ending tag mismatch: input line 276 and div in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():   </div> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():         ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:307: parser error : Specification mandate value for attribute data-pjax-container in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): ntainer" class="repository-content context-loader-container" data-pjax-container in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                                                                ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:315: parser error : Specification mandate value for attribute data-pjax in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): <a href="/MineForeman/MinePeon-Updates/find/master" data-pjax data-hotkey="t" cl in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                                               ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:315: parser error : attributes construct error in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): <a href="/MineForeman/MinePeon-Updates/find/master" data-pjax data-hotkey="t" cl in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                                               ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:315: parser error : Couldn't find end of Start Tag a line 315 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): <a href="/MineForeman/MinePeon-Updates/find/master" data-pjax data-hotkey="t" cl in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                                               ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:315: parser error : Opening and ending tag mismatch: div line 307 and a in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): -hotkey="t" class="js-show-file-finder" style="display:none">Show File Finder</a in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                                                                ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:330: parser error : Specification mandate value for attribute data-pjax in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): ss="select-menu-modal-holder js-menu-content js-navigation-container" data-pjax  in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                                                                ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:330: parser error : attributes construct error in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): ss="select-menu-modal-holder js-menu-content js-navigation-container" data-pjax  in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                                                                ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:330: parser error : Couldn't find end of Start Tag div line 330 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): ss="select-menu-modal-holder js-menu-content js-navigation-container" data-pjax  in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                                                                ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:341: parser error : Opening and ending tag mismatch: input line 340 and div in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():         </div> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():               ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:462: parser error : Entity 'hellip' not defined in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): ejump-input js-jump-to-line-field" type="text" placeholder="Jump to line&hellip; in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                                                                ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:462: parser error : Specification mandate value for attribute autofocus in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():  js-jump-to-line-field" type="text" placeholder="Jump to line&hellip;" autofocus in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                                                                                ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:464: parser error : Opening and ending tag mismatch: input line 462 and form in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():   </form> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():          ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:465: parser error : Opening and ending tag mismatch: form line 461 and div in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): </div> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():       ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:494: parser error : Entity 'copy' not defined in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():       <li>&copy; 2014 <span title="0.02378s from github-fe127-cp1-prd.iad.github in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():                 ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:529: parser error : Opening and ending tag mismatch: div line 73 and body in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():   </body> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():          ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:530: parser error : Opening and ending tag mismatch: div line 65 and html in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): </html> in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():        ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:532: parser error : Premature end of data in tag body line 63 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():  in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:532: parser error : Premature end of data in tag link line 26 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():  in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:532: parser error : Premature end of data in tag link line 25 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():  in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:532: parser error : Premature end of data in tag meta line 24 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():  in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:532: parser error : Premature end of data in tag meta line 23 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():  in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:532: parser error : Premature end of data in tag meta line 10 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():  in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:532: parser error : Premature end of data in tag meta line 9 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():  in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:532: parser error : Premature end of data in tag head line 8 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():  in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml:532: parser error : Premature end of data in tag html line 7 in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file():  in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Warning:  simplexml_load_file(): ^ in /opt/minepeon/etc/cron.d/hourly/DONATE on line 7
PHP Notice:  Trying to get property of non-object in /opt/minepeon/etc/cron.d/hourly/DONATE on line 8
PHP Notice:  Trying to get property of non-object in /opt/minepeon/etc/cron.d/hourly/DONATE on line 9

**Comment by mariogrip** [comment]
you are not using raw.github.com, you are using this https://github.com/MineForeman/MinePeon-Updates/blob/master/update.xml

**Comment by MineForeman** [comment]
Yeah, that fixed it, back to my testing/release ;) .

**Comment by mariogrip** [comment]
Instead of "chatting" here, why are we not using skype?

**Comment by MineForeman** [comment]
Your offline

**Pull request merged**
